/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PdfAnnotation = IDL.Record({
  'content' : IDL.Text,
  'color' : IDL.Text,
  'pageNumber' : IDL.Nat,
  'yPosition' : IDL.Nat,
  'xPosition' : IDL.Nat,
  'annotationType' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const PdfFileMetaData = IDL.Record({
  'blobKey' : ExternalBlob,
  'size' : IDL.Nat,
  'isFavorite' : IDL.Bool,
  'filename' : IDL.Text,
  'pageCount' : IDL.Nat,
  'uploadedAt' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Bookmark = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : Time,
  'pageNumber' : IDL.Nat,
  'fileId' : IDL.Text,
});
export const PremiumUserProfile = IDL.Record({
  'username' : IDL.Text,
  'isPremium' : IDL.Bool,
  'premiumExpiresAt' : IDL.Opt(Time),
  'stripeCustomerId' : IDL.Text,
});
export const FeatureUsageLog = IDL.Record({
  'timestamp' : Time,
  'featureName' : IDL.Text,
});
export const FileOperation = IDL.Record({
  'operationType' : IDL.Text,
  'newBlobKey' : IDL.Opt(ExternalBlob),
  'fileId' : IDL.Text,
  'timestamp' : Time,
  'newName' : IDL.Opt(IDL.Text),
});
export const ReadingProgress = IDL.Record({
  'createdAt' : Time,
  'fileId' : IDL.Text,
  'lastPageRead' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnotation' : IDL.Func([IDL.Text, PdfAnnotation], [], []),
  'addBookmark' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addFileMetaData' : IDL.Func([IDL.Text, PdfFileMetaData], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPremiumStatus' : IDL.Func([IDL.Principal, Time], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAnnotationsForFile' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteFileMetaData' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'getAllFileMetaData' : IDL.Func([], [IDL.Vec(PdfFileMetaData)], ['query']),
  'getAnnotationsByFileId' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(PdfAnnotation)],
      ['query'],
    ),
  'getBookmarks' : IDL.Func([IDL.Principal], [IDL.Vec(Bookmark)], ['query']),
  'getCallerFileMetaData' : IDL.Func([], [IDL.Vec(PdfFileMetaData)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PremiumUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeatureUsageLogs' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FeatureUsageLog)],
      ['query'],
    ),
  'getFileMetaData' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(PdfFileMetaData)],
      ['query'],
    ),
  'getFileOperationsInRange' : IDL.Func(
      [IDL.Principal, Time, Time],
      [IDL.Vec(FileOperation)],
      ['query'],
    ),
  'getPremiumSubscribers' : IDL.Func(
      [],
      [IDL.Vec(PremiumUserProfile)],
      ['query'],
    ),
  'getReadingProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ReadingProgress)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PremiumUserProfile)],
      ['query'],
    ),
  'getUserProfiles' : IDL.Func([], [IDL.Vec(PremiumUserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'logFeatureUsage' : IDL.Func([IDL.Text], [], []),
  'recordFileOperation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'recordMergeOperation' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
      [],
      [],
    ),
  'recordSplitOperation' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
  'renameFile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'revokePremiumStatus' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([PremiumUserProfile], [], []),
  'saveReadingProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleFavorite' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCallerUserProfile' : IDL.Func([PremiumUserProfile], [], []),
  'updateFileMetaData' : IDL.Func([IDL.Text, PdfFileMetaData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PdfAnnotation = IDL.Record({
    'content' : IDL.Text,
    'color' : IDL.Text,
    'pageNumber' : IDL.Nat,
    'yPosition' : IDL.Nat,
    'xPosition' : IDL.Nat,
    'annotationType' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const PdfFileMetaData = IDL.Record({
    'blobKey' : ExternalBlob,
    'size' : IDL.Nat,
    'isFavorite' : IDL.Bool,
    'filename' : IDL.Text,
    'pageCount' : IDL.Nat,
    'uploadedAt' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Bookmark = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : Time,
    'pageNumber' : IDL.Nat,
    'fileId' : IDL.Text,
  });
  const PremiumUserProfile = IDL.Record({
    'username' : IDL.Text,
    'isPremium' : IDL.Bool,
    'premiumExpiresAt' : IDL.Opt(Time),
    'stripeCustomerId' : IDL.Text,
  });
  const FeatureUsageLog = IDL.Record({
    'timestamp' : Time,
    'featureName' : IDL.Text,
  });
  const FileOperation = IDL.Record({
    'operationType' : IDL.Text,
    'newBlobKey' : IDL.Opt(ExternalBlob),
    'fileId' : IDL.Text,
    'timestamp' : Time,
    'newName' : IDL.Opt(IDL.Text),
  });
  const ReadingProgress = IDL.Record({
    'createdAt' : Time,
    'fileId' : IDL.Text,
    'lastPageRead' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnotation' : IDL.Func([IDL.Text, PdfAnnotation], [], []),
    'addBookmark' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addFileMetaData' : IDL.Func([IDL.Text, PdfFileMetaData], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPremiumStatus' : IDL.Func([IDL.Principal, Time], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAnnotationsForFile' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteFileMetaData' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'getAllFileMetaData' : IDL.Func([], [IDL.Vec(PdfFileMetaData)], ['query']),
    'getAnnotationsByFileId' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(PdfAnnotation)],
        ['query'],
      ),
    'getBookmarks' : IDL.Func([IDL.Principal], [IDL.Vec(Bookmark)], ['query']),
    'getCallerFileMetaData' : IDL.Func(
        [],
        [IDL.Vec(PdfFileMetaData)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PremiumUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeatureUsageLogs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FeatureUsageLog)],
        ['query'],
      ),
    'getFileMetaData' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(PdfFileMetaData)],
        ['query'],
      ),
    'getFileOperationsInRange' : IDL.Func(
        [IDL.Principal, Time, Time],
        [IDL.Vec(FileOperation)],
        ['query'],
      ),
    'getPremiumSubscribers' : IDL.Func(
        [],
        [IDL.Vec(PremiumUserProfile)],
        ['query'],
      ),
    'getReadingProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ReadingProgress)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PremiumUserProfile)],
        ['query'],
      ),
    'getUserProfiles' : IDL.Func([], [IDL.Vec(PremiumUserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'logFeatureUsage' : IDL.Func([IDL.Text], [], []),
    'recordFileOperation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'recordMergeOperation' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
        [],
        [],
      ),
    'recordSplitOperation' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
    'renameFile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'revokePremiumStatus' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([PremiumUserProfile], [], []),
    'saveReadingProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleFavorite' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCallerUserProfile' : IDL.Func([PremiumUserProfile], [], []),
    'updateFileMetaData' : IDL.Func([IDL.Text, PdfFileMetaData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };