/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bookmark {
  'title' : string,
  'createdAt' : Time,
  'pageNumber' : bigint,
  'fileId' : string,
}
export type ExternalBlob = Uint8Array;
export interface FeatureUsageLog { 'timestamp' : Time, 'featureName' : string }
export interface FileOperation {
  'operationType' : string,
  'newBlobKey' : [] | [ExternalBlob],
  'fileId' : string,
  'timestamp' : Time,
  'newName' : [] | [string],
}
export interface PdfAnnotation {
  'content' : string,
  'color' : string,
  'pageNumber' : bigint,
  'yPosition' : bigint,
  'xPosition' : bigint,
  'annotationType' : string,
}
export interface PdfFileMetaData {
  'blobKey' : ExternalBlob,
  'size' : bigint,
  'isFavorite' : boolean,
  'filename' : string,
  'pageCount' : bigint,
  'uploadedAt' : Time,
}
export interface PremiumUserProfile {
  'username' : string,
  'isPremium' : boolean,
  'premiumExpiresAt' : [] | [Time],
  'stripeCustomerId' : string,
}
export interface ReadingProgress {
  'createdAt' : Time,
  'fileId' : string,
  'lastPageRead' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  /**
   * / File operation, such as renaming, toggling favorite status, splitting, merging, or deleting.
   */
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnotation' : ActorMethod<[string, PdfAnnotation], undefined>,
  'addBookmark' : ActorMethod<[string, bigint, string], undefined>,
  'addFileMetaData' : ActorMethod<[string, PdfFileMetaData], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPremiumStatus' : ActorMethod<[Principal, Time], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteAnnotationsForFile' : ActorMethod<[Principal, string], undefined>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'deleteFileMetaData' : ActorMethod<[Principal, string], undefined>,
  'getAllFileMetaData' : ActorMethod<[], Array<PdfFileMetaData>>,
  'getAnnotationsByFileId' : ActorMethod<
    [Principal, string],
    Array<PdfAnnotation>
  >,
  'getBookmarks' : ActorMethod<[Principal], Array<Bookmark>>,
  'getCallerFileMetaData' : ActorMethod<[], Array<PdfFileMetaData>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PremiumUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeatureUsageLogs' : ActorMethod<[Principal], Array<FeatureUsageLog>>,
  'getFileMetaData' : ActorMethod<[Principal, string], [] | [PdfFileMetaData]>,
  'getFileOperationsInRange' : ActorMethod<
    [Principal, Time, Time],
    Array<FileOperation>
  >,
  'getPremiumSubscribers' : ActorMethod<[], Array<PremiumUserProfile>>,
  'getReadingProgress' : ActorMethod<[Principal], Array<ReadingProgress>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PremiumUserProfile]>,
  'getUserProfiles' : ActorMethod<[], Array<PremiumUserProfile>>,
  /**
   * / PDF file metadata on the platform.
   */
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'logFeatureUsage' : ActorMethod<[string], undefined>,
  'recordFileOperation' : ActorMethod<
    [string, string, [] | [string], [] | [ExternalBlob]],
    undefined
  >,
  'recordMergeOperation' : ActorMethod<
    [string, Array<string>, ExternalBlob],
    undefined
  >,
  'recordSplitOperation' : ActorMethod<
    [string, Array<string>, Array<ExternalBlob>],
    undefined
  >,
  'renameFile' : ActorMethod<[string, string], undefined>,
  'revokePremiumStatus' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[PremiumUserProfile], undefined>,
  'saveReadingProgress' : ActorMethod<[string, bigint], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleFavorite' : ActorMethod<[string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCallerUserProfile' : ActorMethod<[PremiumUserProfile], undefined>,
  'updateFileMetaData' : ActorMethod<[string, PdfFileMetaData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];